### PR TITLE
Add support for multiple connected clients (fixes #21)

### LINKED ISSUE #21: Add instance ID to handler callback
Warning: I have not a damn clue what I'm talking about when it comes to node, javascript, or perhaps literally anything.

Is it possible to either attach an opaque callback object or otherwise get some sort of instance ID with the callbacks so that if multiple people use the portal simultaneously, a host application can differentiate between the two users?

Unless that's already available, and I'm an idiot...

### PR DESCRIPTION
**Pull request by trisk**
This adds an optional first parameter (actually `session.data` internally) to all handlers to allow use of session-specific data. Each successful request with `auth_token` that gets an `auth_ticket` response is considered a new session. (Not sure if it handles renewals without discarding the previous session).

### CODE REVIEW

**Comment by trisk** [comment]
Don't merge this yet, it's unhappy with we see a response with two empty Buffers in `returns` on initial request with a single GetPlayer.  (This normally causes the app to retry the request, which then succeeds with the correct single Buffer in `returns`). Since this cycles `auth_tickets` between responses to the same request (same session), fixing this correctly should also fix the ticket renewal handling.

**Comment by trisk** [comment]
I think I've fixed it now. The strategy is to look up the session first by auth ticket, then search by request ID. The auth ticket info is updated from every response so we will match the correct session if a subsequent request starts using it. If a retry happens with different auth info (because of a response requiring reauth) we will still locate the session because the request ID will match the previous one.

Also ignore empty return entries which can appear in responses when a reauth is needed.

**Comment by trisk** [comment]
I'd like to merge this soon so we can start updating other features and examples to take advantage of it. Would like to have a sanity check of the design, though. :) The session expiration management could be improved.

**Comment by rastapasta** [comment]
Hey hey @trisk - thanks again for the wonderful contribution, great that u found a neat way to do it after mentioning it on discord - just coming home after a day off, back to the machines, will coffee me, check it, merge it :) cheers!

**Comment by trisk** [comment]
Oops, found and fixed a typo just now (`sessions =` instead of `session =`) in the lookup by request ID.

**Comment by rastapasta** [comment]
Thank yooooou!! LGTM! (ha, first time I ever used that term, training the github slang :D )

**Pull request merged**
