### PR TITLE
Add embedded Google Maps to ingame radar example

### PR DESCRIPTION
**Pull request by trisk**
This replaces photos of Poké Stops with a map of your location and nearby wild Pokémon, using the Google Static Maps API.

### CODE REVIEW

**Comment by trisk** [comment]
Example screenshot of map

**Comment by rubenvereecken** [comment]
Hey trisk, we've been wanting to implement this over at [Enhanced](https://github.com/PokemonGo-Enhanced/Enhanced-Backend) for some time now. 

Would you be okay with us borrowing your implementation?

**Comment by rastapasta** [comment]
@trisk what an amazing idea, heaps of thanks for the implementation!!

**Comment by trisk** [comment]
@rubenvereecken Sure! (You don't need to ask me if you include the MIT license text with your project, which I would suggest anyway since you don't have license info yet 😄). Note that Static Maps has a limit on 5 custom icons (the other markers will show up as pins).

**Pull request merged**
