### PR TITLE
Preserve unknown fields when parsing any protobufs

### PR DESCRIPTION
**Pull request by trisk**
This should address #144

### CODE REVIEW

**Comment by trisk** [comment]
I don't know if we have to strip the `$unknownFields` field when reserialising though.

**Comment by rastapasta** [comment]
I doubt that the library will worry - might be better to test though.. maybe by temporally removing a field from the proto desc? Cheers!

**Comment by trisk** [comment]
Looks like node-protobuf only looks for fields named in the message definition, so the extra property on the JS object (which is present as an empty array even if no unknown fields exist) won't be a problem.

**Comment by rastapasta** [comment]
Thanks a lot for checking it out!

**Pull request merged**
